name: neurosetta
channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - graph-tool
  - pyqt
  - gudhi
  - pykdtree
  - vedo
  - numpy
  - pandas
  - scipy  
  - hdbscan
  - tqdm
  - fastcluster